require('dotenv').config();const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken');const {PrismaClient}=require('@prisma/client');const {z}=require('zod');
const app=express(),prisma=new PrismaClient();app.use(cors());app.use(express.json());
const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Authentication required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({message:'Invalid or expired token'})}}
function roles(...allowed){return (req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({message:'Insufficient permissions'})}
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'CAD Point CRM API'}));
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=z.object({email:z.string().email(),password:z.string().min(6)}).parse(req.body);const u=await prisma.user.findUnique({where:{email}});if(!u||!u.isActive||!(await bcrypt.compare(password,u.passwordHash)))return res.status(401).json({message:'Invalid credentials'});const token=jwt.sign({id:u.id,email:u.email,role:u.role,name:u.name},JWT_SECRET,{expiresIn:'8h'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(400).json({message:e.message})}});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/leads',auth,async(req,res)=>{const data=await prisma.lead.findMany({include:{source:true,assignedCounsellor:{select:{id:true,name:true}},followUps:{orderBy:{scheduledAt:'asc'},take:1}},orderBy:{createdAt:'desc'}});res.json({data,total:data.length})});
app.post('/api/leads',auth,async(req,res)=>{try{const body=z.object({firstName:z.string().min(2),lastName:z.string().optional(),phone:z.string().min(8),email:z.string().email().optional(),sourceId:z.string().uuid().optional(),interestedCourse:z.string().optional()}).parse(req.body);const lead=await prisma.lead.create({data:{...body,leadNumber:'LD-'+Date.now()}});res.status(201).json({data:lead})}catch(e){res.status(400).json({message:e.message})}});
app.patch('/api/leads/:id/status',auth,async(req,res)=>{const lead=await prisma.lead.findUnique({where:{id:req.params.id}});if(!lead)return res.status(404).json({message:'Lead not found'});const status=z.enum(['NEW','CONTACTED','FOLLOW_UP','INTERESTED','DEMO_SCHEDULED','NEGOTIATION','ADMISSION','NOT_INTERESTED','LOST','INVALID']).parse(req.body.status);const updated=await prisma.$transaction([prisma.lead.update({where:{id:lead.id},data:{status}}),prisma.leadStatusHistory.create({data:{leadId:lead.id,oldStatus:lead.status,newStatus:status,changedBy:req.user.id}})]);res.json({data:updated[0]})});
app.get('/api/courses',auth,async(req,res)=>res.json({data:await prisma.course.findMany({orderBy:{name:'asc'}})}));
app.post('/api/courses',auth,roles('SUPER_ADMIN','ADMIN'),async(req,res)=>{const c=await prisma.course.create({data:{courseCode:req.body.courseCode,name:req.body.name,description:req.body.description,standardFee:req.body.standardFee,durationDays:req.body.durationDays,durationHours:req.body.durationHours}});res.status(201).json({data:c})});
app.get('/api/batches',auth,async(req,res)=>res.json({data:await prisma.batch.findMany({include:{course:true,trainer:{select:{id:true,name:true}}},orderBy:{startDate:'desc'}})}));
app.get('/api/students',auth,async(req,res)=>res.json({data:await prisma.student.findMany({include:{admissions:{include:{course:true,batch:true,payments:true}}},orderBy:{createdAt:'desc'}})}));
app.get('/api/payments',auth,async(req,res)=>res.json({data:await prisma.payment.findMany({include:{admission:{include:{student:true,course:true}}},orderBy:{paymentDate:'desc'}})}));
app.get('/api/dashboard',auth,async(req,res)=>{const [leads,admissions,payments,outstanding]=await Promise.all([prisma.lead.count(),prisma.admission.count(),prisma.payment.aggregate({where:{status:'SUCCESS'},_sum:{amount:true}}),prisma.admission.findMany({select:{finalFee:true,payments:{where:{status:'SUCCESS'},select:{amount:true}}}})]);const due=outstanding.reduce((s,a)=>s+Number(a.finalFee)-a.payments.reduce((x,p)=>x+Number(p.amount),0),0);res.json({leads,admissions,revenue:Number(payments._sum.amount||0),outstanding:due})});
app.listen(process.env.PORT||5000,()=>console.log('CAD Point CRM API on port '+(process.env.PORT||5000)));
